In [1]:
from sklearn.datasets import fetch_openml

In [2]:
import pandas as pd

In [3]:
titanic=fetch_openml('titanic',version=1,as_frame=True)
df=titanic.frame
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

## 🧹 2. Feature Engineering & Encoding

In [5]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   category
 2   name       1309 non-null   object
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   category
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: category(3), float64(3), int64(3), object(5)
memory usage: 116.8+ KB

In [12]:
# 🔹 (A) Missing Value Handling

df['age'].fillna(df['age'].median(),inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0],inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24196\4040773508.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].median(),inplace=True)

In [13]:
# 🔹 (B) Label Encoding

In [15]:
df['sex']

0       female
1         male
2       female
3         male
4       female
         ...
1304    female
1305    female
1306      male
1307      male
1308      male
Name: sex, Length: 1309, dtype: category
Categories (2, object): ['female', 'male']

In [14]:
from sklearn.preprocessing import LabelEncoder

In [16]:
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])

In [17]:
# 🔹 (C) One-Hot Encoding

In [18]:
df['embarked']

0       S
1       S
2       S
3       S
4       S
       ..
1304    C
1305    C
1306    C
1307    C
1308    S
Name: embarked, Length: 1309, dtype: category
Categories (3, object): ['C', 'Q', 'S']

In [19]:
df = pd.get_dummies(df, columns=['embarked'], drop_first=True)

In [21]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'boat', 'body', 'home.dest', 'embarked_Q',
       'embarked_S'],
      dtype='object')

In [23]:
# 🔹 (D) Ordinal Encoding

In [24]:
df.head(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,boat,body,home.dest,embarked_Q,embarked_S
0,1,1,"Allen, Miss. Elisabeth Walton",0,29.0000,0,0,24160,211.3375,B5,2,NaN,"St Louis, MO",False,True
1,1,1,"Allison, Master. Hudson Trevor",1,0.9167,1,2,113781,151.5500,C22 C26,11,NaN,"Montreal, PQ / Chesterville, ON",False,True
2,1,0,"Allison, Miss. Helen Loraine",0,2.0000,1,2,113781,151.5500,C22 C26,NaN,NaN,"Montreal, PQ / Chesterville, ON",False,True
3,1,0,"Allison, Mr. Hudson Joshua Creighton",1,30.0000,1,2,113781,151.5500,C22 C26,NaN,135.0,"Montreal, PQ / Chesterville, ON",False,True
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",0,25.0000,1,2,113781,151.5500,C22 C26,NaN,NaN,"Montreal, PQ / Chesterville, ON",False,True
5,1,1,"Anderson, Mr. Harry",1,48.0000,0,0,19952,26.5500,E12,3,NaN,"New York, NY",False,True
6,1,1,"Andrews, Miss. Kornelia Theodosia",0,63.0000,1,0,13502,77.9583,D7,10,NaN,"Hudson, NY",False,True
7,1,0,"Andrews, Mr. Thomas Jr",1,39.0000,0,0,112050,0.0000,A36,NaN,NaN,"Belfast, NI",False,True
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",0,53.0000,2,0,11769,51.4792,C101,D,NaN,"Bayside, Queens, NY",False,True
9,1,0,"Artagaveytia, Mr. Ramon",1,71.0000,0,0,PC 17609,49.5042,NaN,NaN,22.0,"Montevideo, Uruguay",False,False

In [26]:
df['pclass'].unique()

array([1, 2, 3], dtype=int64)

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
df['class']=OrdinalEncoder().fit_transform(df[['pclass']])

In [30]:
# 🔹 (E) Feature Scaling

In [35]:
# RobustScaler (outlier safe)
from sklearn.preprocessing import RobustScaler

In [44]:
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

outlier_summary = {}

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    outlier_summary[col] = len(outliers)

print(outlier_summary)

{'pclass': 0, 'age': 101, 'sibsp': 57, 'parch': 307, 'fare': 171, 'body': 0, 'class': 0}

In [45]:
from sklearn.preprocessing import RobustScaler

cols = ['age', 'fare', 'sibsp', 'parch']

scaler = RobustScaler()

df[cols] = scaler.fit_transform(df[cols])

In [46]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'boat', 'body', 'home.dest', 'embarked_Q',
       'embarked_S', 'class'],
      dtype='object')

In [ ]:
# 🔹 (F) Feature Creation

In [49]:
df.head(5)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,boat,body,home.dest,embarked_Q,embarked_S,class,family_size
0,1,1,"Allen, Miss. Elisabeth Walton",0,0.076923,0.0,0.0,24160,8.421302,B5,2,NaN,"St Louis, MO",False,True,0.0,1.0
1,1,1,"Allison, Master. Hudson Trevor",1,-2.083331,1.0,2.0,113781,5.864007,C22 C26,11,NaN,"Montreal, PQ / Chesterville, ON",False,True,0.0,4.0
2,1,0,"Allison, Miss. Helen Loraine",0,-2.000000,1.0,2.0,113781,5.864007,C22 C26,NaN,NaN,"Montreal, PQ / Chesterville, ON",False,True,0.0,4.0
3,1,0,"Allison, Mr. Hudson Joshua Creighton",1,0.153846,1.0,2.0,113781,5.864007,C22 C26,NaN,135.0,"Montreal, PQ / Chesterville, ON",False,True,0.0,4.0
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",0,-0.230769,1.0,2.0,113781,5.864007,C22 C26,NaN,NaN,"Montreal, PQ / Chesterville, ON",False,True,0.0,4.0

In [48]:
df['family_size'] = df['sibsp'] + df['parch'] + 1

In [50]:
# 🔹 (G) Binning / Discretization

In [51]:
df['age_group'] = pd.cut(df['age'], bins=[0,18,40,80], labels=['Child','Adult','Old'])

In [53]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'boat', 'body', 'home.dest', 'embarked_Q',
       'embarked_S', 'class', 'family_size', 'age_group'],
      dtype='object')

In [56]:
df['age_group']

0       Child
1         NaN
2         NaN
3       Child
4         NaN
        ...
1304      NaN
1305      NaN
1306      NaN
1307      NaN
1308    Child
Name: age_group, Length: 1309, dtype: category
Categories (3, object): ['Child' < 'Adult' < 'Old']

In [58]:
# (H) Date-time (example concept)

In [60]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'boat', 'body', 'home.dest', 'embarked_Q',
       'embarked_S', 'class', 'family_size', 'age_group'],
      dtype='object')

In [61]:
df['year'] = pd.to_datetime(df['date']).dt.year
df['month'] = pd.to_datetime(df['date']).dt.month

KeyError: 'date'

## ✂️ 3. Train-Test Split

In [64]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'boat', 'body', 'home.dest', 'embarked_Q',
       'embarked_S', 'class', 'family_size', 'age_group'],
      dtype='object')

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop('survived', axis=1)
y = df['survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

## ⚠️ 4. Data Leakage (IMPORTANT)

In [71]:
# scaler.fit(X) it's dangerous

In [ ]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

ValueError: could not convert string to float: 'Dika, Mr. Mirko'

📊 5. Stratified Split (important for imbalance)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
        random_state=42
)

## 🔁 6. Cross Validation

In [74]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

scores = cross_val_score(model, X, y, cv=5)

print(scores.mean())

ValueError:
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 856, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1459, in fit
    X, y = validate_data(
           ^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py", line 3055, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py", line 1327, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py", line 970, in check_array
    array = array.astype(new_dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 430, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Harris, Mrs. Henry Birkhardt (Irene Wallach)'

--------------------------------------------------------------------------------
4 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\model_selection\_validation.py", line 856, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py", line 1459, in fit
    X, y = validate_data(
           ^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py", line 3055, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py", line 1327, in check_X_y
    X = check_array(
        ^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py", line 970, in check_array
    array = array.astype(new_dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\generic.py", line 6643, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 430, in astype
    return self.apply(
           ^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\blocks.py", line 758, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 237, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 182, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\ProgramData\anaconda3\Lib\site-packages\pandas\core\dtypes\astype.py", line 133, in _astype_nansafe
    return arr.astype(dtype, copy=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Allen, Miss. Elisabeth Walton'

## ⚖️ 7. Imbalanced Data Handling

In [75]:
# 🔹 SMOTE

In [76]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_res, y_res = smote.fit_resample(X, y)

ImportError: cannot import name '_safe_tags' from 'sklearn.utils._tags' (C:\Users\HP\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\_tags.py)

In [77]:
# 🔹 SMOTETomek

In [78]:
from imblearn.combine import SMOTETomek

smote_tomek = SMOTETomek()
X_res, y_res = smote_tomek.fit_resample(X, y)

AttributeError: 'SMOTETomek' object has no attribute '_validate_data'

In [79]:
# 🔹 Class Weight
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced')

## 🧱 8. Pipeline (VERY IMPORTANT)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
from sklearn.linear_model import LogisticRegression

pipe = Pipeline([
    ('scaler', RobustScaler()),
    ('model', LogisticRegression())
])

pipe.fit(X_train, y_train)
pipe.score(X_test, y_test)

ValueError: could not convert string to float: "McCarthy, Miss. Catherine 'Katie'"